### ISSUE TITLE
v-model[type=] is not supported

### ISSUE THREAD

**Issue by DM2489** [vuejs/jsx#15]
It looks like components with v-model are not being correctly flagged as a component. This means the `isComponent` check is failing and falling through to the error.

For example:

```
render() {
    return (
        <div>
            <vue-multiselect v-model={this.model} />
            <b-form-checkbox v-model={this.status} />
        </div>
    );
}
```
is not being treated as a component.

**Comment by DM2489** [comment]
Seems to be that `babel-sugar-v-model` -> `src` -> `index,js` is testing whether something is a component based on whether is a `JSXMemberExpression`, or if the first character is between `A` and `Z` (note the capitalisation).

This seems to be like quite an incompatibility issue. Vue does not force components to be capitalised:
https://vuejs.org/v2/guide/components.html

Note also that the old transform - https://github.com/nickmessing/babel-plugin-jsx-v-model, does not force the same capitalisation rules.

**Comment by nickmessing** [comment]
We discussed this with the team when I was first starting this project. Decision to limit only to PascalCase component names for the sugar plugin was based on our style-guide, not on the API that Vue supports.

You can see the arguments for having PascalCased components [here](https://vuejs.org/v2/style-guide/#Component-name-casing-in-JS-JSX-strongly-recommended)

**Comment by nickmessing** [comment]
@DM2489, that's a very good point, I will add support for kebab-case component but with a big warning, if we want to expand the JSX community and follow the style guide properly, we should ask all libraries to export components as an option for direct usage instead of just registering them to Vue global namespace.

**Comment by DM2489** [comment]
@nickmessing I agree 100%. Thank you for agreeing to support `kebab-case` until the style guide is updated and 3rd parties have had chance to sort their code accordingly.

**Comment by nickmessing** [comment]
Actually, I think there is another thing that would be good to support, since we recommend PascalCased components in both templates and JSX, that should be supported by all component libraries, and so, instead of always assuming it's an `Identifier`, we could check if this Identifier is ever declared in current scope, if not, use it as string, for example:
```jsx
import MyComponent from './MyComponent'

export default {
  render () {
    return (
      <div>
        <MyComponent />
        <SomeGlobalComponent />
      </div>
    }
  }
}
```
to transpile to:
```jsx
import MyComponent from './MyComponent'

export default {
  render () {
    return h('div', [h(MyComponent), h('SomeGlobalComponent')])
  }
}
```

If we add this and support for kebab-case global component for `vModel`, this should cover pretty much everything.

Thoughts @DM2489, @znck, @chrisvfritz, @yyx990803?

**Comment by DM2489** [comment]
@nickmessing Seems sensible to me.

**Comment by znck** [comment]
> check if this Identifier is ever declared in current scope, if not, use it as string

It feels very convenient and allows using globally registered components. I got nothing against it. 👍 from me.

**Comment by chrisvfritz** [comment]
@nickmessing I think a simpler change would be in Vue itself, to make global components registered with kebab-case automatically work with PascalCase as well. Right now, it's only the other way around.

**Comment by nickmessing** [comment]
@chrisvfritz, but the PRs area already up and tests work fine, just by using `html-tags` and `svg-tags` that works fine.

**Comment by chrisvfritz** [comment]
@nickmessing If we assume every kebab-case element is a component though, won't it be impossible to use custom elements defined by other libraries, like A-Frame?

There's also a PR ready to be merged for the change in Vue, marked for release in 2.6.
