### ISSUE TITLE
auto inject h error with tsx vue-class-component

### ISSUE THREAD

**Issue by theWorkFsz** [vuejs/jsx#62]
like this https://github.com/vuejs/jsx/issues/34 

when you auto inject h  with vue-class-component and tsx will get some thing wrong

build just fine ，no error，but  there will  actually be problems

there is my [example repo](https://github.com/theWorkFsz/ts-vue-auto-inject-h-demo)

`components/test.vue` look like is：
```vue
  
<template>
  <div></div>
</template>
<script lang="tsx">
import { Component, Vue } from "vue-property-decorator";
@Component
export default class App extends Vue {
  test = (h: any) => <div>123</div>;
}
</script>
```

then, the `test.vue` will be  built into this :

```js
/*#__PURE__*/
function (_Vue) {
  Object(inherits["a" /* default */])(App, _Vue);

  function App() {
    var _this;

    Object(classCallCheck["a" /* default */])(this, App);

    // the  _this variable is undefined，I think this is the problem ！
    var h = _this.$createElement;
    _this = Object(possibleConstructorReturn["a" /* default */])(this, Object(getPrototypeOf["a" /* default */])(App).apply(this, arguments));

    _this.test = function (h) {
      return h("div", ["123"]);
    };

    return _this;
  }

  return App;
}(vue_property_decorator["c" /* Vue */]);

```
as you can see the `h`  variable is inject before `_this` definition, then an error occurred

**Comment by LM-G** [comment]
I second that, I have exactly the same issue.

**Comment by theWorkFsz** [comment]
> I second that, I have exactly the same issue.

now i just simply turned off this feature

p.s: if you use vue-cli3, you need to turn off this feature in `@vue/babel-preset-app` config
https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#jsx

**Comment by LM-G** [comment]
It's a pity but for now i reference  `const h = this.$createElement;` at the beginning of all functions returning some jsx element.

Now I only use this feature for pure functional component with `.jsx` extension, it is better than nothing at all.

**Comment by nickmessing** [comment]
This is a terrible idea in the first place, if you use:
```js
import { Component, Vue } from "vue-property-decorator";
@Component
export default class App extends Vue {
  test = (h: any) => <div>123</div>;
}
```
`test` will be a part of `$data` so it's reactive get/set property which is monitored by Vue, that's why you should always use:
```js
import { Component, Vue } from "vue-property-decorator";
@Component
export default class App extends Vue {
  test(h: any) { return <div>123</div> }
}
```

I don't think we are willing to support an anti-pattern by default so you have to turn off auto-inject for it, sorry for that :(

**Comment by LM-G** [comment]
@nickmessing I am using the second pattern with class method and not some attribute returning arrow function. Why are you closing this ?

This is not working:

```typescript
// App.tsx
import { Component, Vue } from "vue-property-decorator";
@Component
export default class App extends Vue {
  render() { return <div>123</div> }
}
```

After further testing, i found out that this auto inject feature only works with `.jsx` files, not `.tsx`. For example:

This is working fine:
```
// Hello.jsx => JSX extension OK
export const Hello = () => <h1>Hello</h1>
```
and this is not working, getting the h is not defined error:
```
// Hello.tsx => TSX extension KO
export const Hello = () => <h1>Hello</h1>
```
As you said, @theWorkFsz will have problems later due to the fact his `test` function will be monitored by Vue and that make no sense at all and you are right. But the real problem here is that `h` createElement function is not injected in class method when using `tsx` components.
