### ISSUE TITLE
vOn:click is not valid jsx prop with semicolon

### ISSUE THREAD

**Issue by eakarpov** [vuejs/jsx#69]
Semicolons are not a valid part of a jsx prop

**Comment by nickmessing** [comment]
@eakarpov, yes, semicolons (`;`) are not, but colons (`:`) are according to the spec.

As you can see in the spec: https://facebook.github.io/jsx/
`JSXAttributeName` can be either `JSXIdentifier` or `JSXNamespacedName`
and `JSXNamespacedName` is just `JSXIdentifier` `:` `JSXIdentifier`
so colon (I assume you mean that since we discussed colons) are a valid part of `JSXAttributeName` as long as it's a single colon separating two `JSXIdentifier`.

P.S. However, they are not allowed in TSX at the moment because TSX does not fully support JSX spec.
