### ISSUE TITLE
onMouseEnter and onMouseOut analogues

### ISSUE THREAD

**Issue by eakarpov** [vuejs/jsx#70]
How to implement v-on:enter and v-on:leave events in vue jsx?

**Comment by nickmessing** [comment]
@eakarpov, please use official [chat](https://chat.vuejs.org/) or [forum](https://fortm.vuejs.org/) to ask questions. Issues are only for bug reports & feature requests.

P.S. `onMouseenter` should work because event name in HTML spec is all-lowercase: https://w3c.github.io/uievents/#event-type-mouseenter
